@del "%USERPROFILE%\SendTo\MagMaker\mag_BB.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\mag_HTML.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\magnet.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\ed2k_link.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\filelist.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\hashonly.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\htext.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\hash_push.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\html.cmd"
@del "%USERPROFILE%\SendTo\MagMaker\torpatch.cmd"
@rd "%USERPROFILE%\SendTo\MagMaker"

@del "%USERPROFILE%\Start Menu\Programs\MagMaker\rhash_max.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\rhash_min.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\rhash_shareaza.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\mag_BB.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\mag_HTML.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\magnet.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\filelist.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\htext.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\hash_push.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\hash_pop.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\html.cmd"
@del "%USERPROFILE%\Start Menu\Programs\MagMaker\torredactor.cmd"
@rd "%USERPROFILE%\Start Menu\Programs\MagMaker"