@rd /S /Q "%USERPROFILE%\SendTo\Copy Link\"
@rd /S /Q "%USERPROFILE%\SendTo\Torrent Editor"
@rd /S /Q "%USERPROFILE%\SendTo\MagMaker"
@rd /S /Q "%USERPROFILE%\SendTo\Marker"
@rd /S /Q "%USERPROFILE%\SendTo\Encoder"

@rd /S /Q "%USERPROFILE%\Start Menu\Programs\Torrent Editor"
@rd /S /Q "%USERPROFILE%\Start Menu\Programs\MagMaker"
@rd /S /Q "%USERPROFILE%\Application Data\Microsoft\Internet Explorer\Quick Launch\Torrent Editor"
@rd /S /Q "%USERPROFILE%\Application Data\Microsoft\Internet Explorer\Quick Launch\MagMaker"